Fix gating upgrade to yield the vms_list
Moving the running_vm check and yield vms_list statements outside
of the non-gating conditional block, so the vms_for_upgrade
fixture will:

- Always yield the vms_list containing at least the
vm_with_instancetypes_for_upgrade VM.
- For non-gating tests, it will create additional VMs
from the data sources and add them to the list.

This ensures that the vms_for_upgrade fixture always yields a
value regardless of whether the test is marked with
@pytest.mark.gating or not, resolving the
  ValueError: vms_for_upgrade did not yield a value error.