net, stability: Fix test_connectivity_of_hot_plugged_sriov_interface
test_connectivity_of_hot_plugged_sriov_interface is failing:
VMInterfaceStatusNotFoundError: Network interface named
sriov-hot-plug-test-network was not found in VM sriov-hot-plug-vm2

The change includes incrementing the timeout of the hotplugged
SR-IOV interface to appear since the 2-minute timeout is not
sufficient.
During this timeout we expect the seamless migration post
hotplug to complete and guest agent to connect and VMI status
updated but the virt-handler.

Signed-off-by: Asia Khromov <azhivovk@redhat.com>