net, sriov: Split fixtures
test_connectivity_of_hot_plugged_sriov_interface is failing:
VMInterfaceStatusNotFoundError: Network interface named
sriov-hot-plug-test-network was not found in VM sriov-hot-plug-vm2
And VM2 must-gather logs are missing due to early teardown.

VM2 is torndown by __exit__ before must-gather takes action.
The fix is to use separate fixtures for VM creation and SR-IOV
interface hotplug - then must-gather runs right after setup error.

Signed-off-by: Asia Khromov <azhivovk@redhat.com>
Assisted-by: Claude Sonnet 4.6 <noreply@anthropic.com>