net, localnet: fix import (#5326)
##### What this PR does / why we need it:
Refactoring PR was merged before localnet changes, causing import issue
in main when running localnet tests + pre-commit error + tox error

`ImportError: cannot import name 'nodenetworkconfigurationpolicy' from
'tests.network.libs'
(/home/azhivovk/repos/openshift-virtualization-tests/tests/network/libs/__init__.py)`

##### Which issue(s) this PR fixes:
Fix import in localnet

##### Special notes for reviewer: -

##### jira-ticket: -
<!-- full-ticket-url needs to be provided. This would add a link to the
pull request to the jira and close it when the pull request is merged
If the task is not tracked by a Jira ticket, just write "NONE".
-->


<!-- This is an auto-generated comment: release notes by coderabbit.ai
-->

## Summary by CodeRabbit

* **Chores**
* Internal refactoring of test infrastructure imports to improve code
organization and maintainability.

<!-- end of auto-generated comment: release notes by coderabbit.ai -->

Signed-off-by: Asia Khromov <azhivovk@redhat.com>